export interface Artwork {
  id: string
  title: string
  year: string
  medium: string
  size: string
  image: string
  series: string
}

// Updated artwork collection - 26 high-quality paintings
export const artworks: Artwork[] = [
  {
    id: 'art-01',
    title: 'Noosa Main Beach Sunset',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/1 Noosa Main Beach Sunset.jpg',
    series: '2024',
  },
  {
    id: 'art-02',
    title: 'Dandenong Ranges Botanic Garden',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/2 Dandenong Ranges Botanic Garden.jpg',
    series: '2024',
  },
  {
    id: 'art-03',
    title: 'By the Sea of Galilee',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/3 BY THE SEA OF GALILEE.jpg',
    series: '2024',
  },
  {
    id: 'art-04',
    title: 'Hatbalah - To Be Baptized in the River Jordan',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/4 Hatbalah-- To be baptized in the River Jordan.jpg',
    series: '2024',
  },
  {
    id: 'art-05',
    title: 'Seeking in the Wilderness - Masada',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/5 Seeking in the wilderness.jpg',
    series: '2024',
  },
  {
    id: 'art-06',
    title: 'Cradle',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/6 CRADLE.jpg',
    series: '2024',
  },
  {
    id: 'art-07',
    title: 'Dancing',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/7 DANCING.jpg',
    series: '2024',
  },
  {
    id: 'art-08',
    title: 'Spring, Botanic Garden',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/8 SPRING, BOTANIC GARDEN.jpg',
    series: '2024',
  },
  {
    id: 'art-09',
    title: 'Summer, Sunflowers',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/9 SUMMER,SUNFLOWERS.jpg',
    series: '2024',
  },
  {
    id: 'art-10',
    title: 'Longing in Autumn',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/10 LONGING IN AUTUMN.jpg',
    series: '2024',
  },
  {
    id: 'art-11',
    title: 'Winter - From Wintry Hardship Comes the Plum Blossom\'s Scent',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/11 WINTER.jpg',
    series: '2024',
  },
  {
    id: 'art-12',
    title: 'Ocean',
    year: '2024',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/12 OCEAN.jpg',
    series: '2024',
  },
  {
    id: 'art-13',
    title: 'Dancer I',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/13 DANCER 1.jpg',
    series: '2023',
  },
  {
    id: 'art-14',
    title: 'Dancer II',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/14 DANCER 2.jpg',
    series: '2023',
  },
  {
    id: 'art-15',
    title: 'Dancer III',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/15 DANCER 3.jpg',
    series: '2023',
  },
  {
    id: 'art-16',
    title: 'Dancer IV',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/16 DANCER 4.jpg',
    series: '2023',
  },
  {
    id: 'art-17',
    title: 'Vineyard',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/17  Vineyard.jpg',
    series: '2023',
  },
  {
    id: 'art-18',
    title: 'A Corner of Garden I',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/18 A Corner of Garden 1.jpg',
    series: '2023',
  },
  {
    id: 'art-19',
    title: 'A Corner of Garden II',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/19 A Corner of Garden 2.jpg',
    series: '2023',
  },
  {
    id: 'art-20',
    title: 'A Corner of Garden III',
    year: '2023',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/20 A Corner of Garden 3.jpg',
    series: '2023',
  },
  {
    id: 'art-21',
    title: 'The Brain\'s Response',
    year: 'Archive',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/21 The Brains Response.jpg',
    series: 'Archive',
  },
  {
    id: 'art-22',
    title: 'Where Eyes Cannot Reach',
    year: 'Archive',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/22 Where eyes cannot reach.jpg',
    series: 'Archive',
  },
  {
    id: 'art-23',
    title: 'Who Am I',
    year: 'Archive',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/23 who am I.jpg',
    series: 'Archive',
  },
  {
    id: 'art-24',
    title: 'Masada Mountain Range I',
    year: 'Archive',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/24Masada mountain range 1.jpg',
    series: 'Archive',
  },
  {
    id: 'art-25',
    title: 'Masada Mountain Range',
    year: 'Archive',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/25Masada mountain range.jpg',
    series: 'Archive',
  },
  {
    id: 'art-26',
    title: 'Tower Hill',
    year: 'Archive',
    medium: 'Mixed media on canvas',
    size: 'Inquire for details',
    image: '/images/artworks/26tower hill.jpg',
    series: 'Archive',
  },
]

export const seriesOrder = [
  { name: '2024', slug: '2024' },
  { name: '2023', slug: '2023' },
  { name: 'Archive', slug: 'archive' },
] as const
